[platformio]
default_envs = c3_oled_72x40_gpio5_6

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  olikraus/U8g2@^2.36.5
build_flags =
  -D SERIAL_BAUD=115200

[env:c3_oled_72x40_gpio5_6]
extends = env
build_flags =
  ${env.build_flags}
  -D OLED_GEOMETRY=72
  -D OLED_SDA=5
  -D OLED_SCL=6

[env:c3_oled_72x40_gpio8_9]
extends = env
build_flags =
  ${env.build_flags}
  -D OLED_GEOMETRY=72
  -D OLED_SDA=8
  -D OLED_SCL=9

[env:c3_oled_128x64_gpio5_6]
extends = env
build_flags =
  ${env.build_flags}
  -D OLED_GEOMETRY=128
  -D OLED_SDA=5
  -D OLED_SCL=6

[env:c3_oled_128x64_gpio8_9]
extends = env
build_flags =
  ${env.build_flags}
  -D OLED_GEOMETRY=128
  -D OLED_SDA=8
  -D OLED_SCL=9
